
build:
	GOOS=linux GOARCH=amd64 go build -o build/release/openai-dispatcher main.go
	
run:
	go run main.go -conf config.local.yaml

deploy: build deploy-server-1 deploy-server-2

deploy-server-1:
	scp build/release/openai-dispatcher huawei-1:/data/webroot/ai-server/openai-dispatcher.new
	ssh huawei-1 'mv /data/webroot/ai-server/openai-dispatcher /data/webroot/ai-server/openai-dispatcher.old && mv /data/webroot/ai-server/openai-dispatcher.new /data/webroot/ai-server/openai-dispatcher'
	ssh huawei-1 'systemctl restart openai-dispatcher'

deploy-server-2:
	scp build/release/openai-dispatcher huawei-2:/data/webroot/ai-server/openai-dispatcher.new
	ssh huawei-2 'mv /data/webroot/ai-server/openai-dispatcher /data/webroot/ai-server/openai-dispatcher.old && mv /data/webroot/ai-server/openai-dispatcher.new /data/webroot/ai-server/openai-dispatcher'
	ssh huawei-2 'systemctl restart openai-dispatcher'

deploy-config:
	scp config.prod.yaml huawei-1:/data/webroot/ai-server/etc/openai-dispatcher.yaml
	scp config.prod.yaml huawei-2:/data/webroot/ai-server/etc/openai-dispatcher.yaml

restart-server:
	ssh huawei-1 'systemctl restart openai-dispatcher'
	ssh huawei-2 'systemctl restart openai-dispatcher'
	
deploy-vultr: build
	scp build/release/openai-dispatcher vultr:/data/webroot/openai-dispatcher/openai-dispatcher.new
	ssh vultr 'mv /data/webroot/openai-dispatcher/openai-dispatcher /data/webroot/openai-dispatcher/openai-dispatcher.old && mv /data/webroot/openai-dispatcher/openai-dispatcher.new /data/webroot/openai-dispatcher/openai-dispatcher'
	ssh vultr 'systemctl restart openai-dispatcher'
	
deploy-aliyun-app: build
	scp build/release/openai-dispatcher aliyun-1:/data/webroot/openai-dispatcher/openai-dispatcher.new
	ssh aliyun-1 'mv /data/webroot/openai-dispatcher/openai-dispatcher /data/webroot/openai-dispatcher/openai-dispatcher.old && mv /data/webroot/openai-dispatcher/openai-dispatcher.new /data/webroot/openai-dispatcher/openai-dispatcher'
	ssh aliyun-1 'systemctl restart openai-dispatcher'

.PHONY: build deploy deploy-server-1 deploy-server-2 deploy-config restart-server deploy-vultr deploy-aliyun-app