
build:
	GOOS=linux GOARCH=amd64 go build -o build/release/openai-dispatcher main.go

deploy: build deploy-server-1 deploy-server-2

deploy-server-1:
	scp build/release/openai-dispatcher huawei-1:/data/webroot/ai-server/openai-dispatcher.new
	ssh huawei-1 'mv /data/webroot/ai-server/openai-dispatcher /data/webroot/ai-server/openai-dispatcher.old && mv /data/webroot/ai-server/openai-dispatcher.new /data/webroot/ai-server/openai-dispatcher'
	ssh huawei-1 'systemctl restart openai-dispatcher'

deploy-server-2:
	scp build/release/openai-dispatcher huawei-2:/data/webroot/ai-server/openai-dispatcher.new
	ssh huawei-2 'mv /data/webroot/ai-server/openai-dispatcher /data/webroot/ai-server/openai-dispatcher.old && mv /data/webroot/ai-server/openai-dispatcher.new /data/webroot/ai-server/openai-dispatcher'
	ssh huawei-2 'systemctl restart openai-dispatcher'

.PHONY: build deploy deploy-server-1 deploy-server-2